// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgGRYl84E9eINF1AqShejd83C7hYWtRA',
    appId: '1:774263534735:web:2008252497ae59b70b6cfa',
    messagingSenderId: '774263534735',
    projectId: 'olta-dc37a',
    authDomain: 'olta-dc37a.firebaseapp.com',
    storageBucket: 'olta-dc37a.appspot.com',
    measurementId: 'G-NCBR7DPNRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVf8R5vslTU7x3voCcBUjz5SJLCoZTdkg',
    appId: '1:774263534735:android:40dd6587aafa2f130b6cfa',
    messagingSenderId: '774263534735',
    projectId: 'olta-dc37a',
    storageBucket: 'olta-dc37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDpe0tdU-6v_i8DdP9JxGzD5n16epocc',
    appId: '1:774263534735:ios:f1eb0a20d4d62d830b6cfa',
    messagingSenderId: '774263534735',
    projectId: 'olta-dc37a',
    storageBucket: 'olta-dc37a.appspot.com',
    iosClientId: '774263534735-qu8ortdfmk5kv77majb5kh771pq65rjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.oltaCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDpe0tdU-6v_i8DdP9JxGzD5n16epocc',
    appId: '1:774263534735:ios:f1eb0a20d4d62d830b6cfa',
    messagingSenderId: '774263534735',
    projectId: 'olta-dc37a',
    storageBucket: 'olta-dc37a.appspot.com',
    iosClientId: '774263534735-qu8ortdfmk5kv77majb5kh771pq65rjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.oltaCoin',
  );
}
